version: '3'

services:
  async-serverapp:
    build: async-serverapp/
    image: async-serverapp
    ports:
      - "8083"
    command: ["java", "-jar", "/app/async-serverapp.jar"]

  async-receiver-pull:
    build: async-receiver-pull/
    image: async-receiver-pull
    ports:
      - "8082"
    command: ["java", "-jar", "/app/async-receiver.jar"]

  async-sender-pull:
    build: async-sender-pull/
    image: async-sender-pull
    ports:
      - "8084"
    command: ["java", "-jar", "/app/async-sender.jar"]

  async-clientapp:
    build: async-clientapp/
    image: async-clientapp
    depends_on:
      - async-serverapp
      - async-receiver-pull
      - async-sender-pull
    ports:
      - "8081"
    command: ["java", "-jar", "/app/async-clientapp.jar"]

  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - async-serverapp
      - async-receiver-pull
      - async-sender-pull
    command: async-serverapp:10992 async-receiver-pull:10991 async-sender-pull:10990