version: '3'

services:
  async-serverapp:
    build: async-serverapp/
    image: async-serverapp
    ports:
      - "8083"
      - "10992"

  async-receiver-pull:
    build: async-receiver-pull/
    image: async-receiver-pull
    depends_on:
      -  async-serverapp
    ports:
      - "10991"
      - "8082"
    links:
      - async-serverapp
    command: ./wait-for-it.sh async-serverapp:10992 --timeout=2 --strict -- java -jar  async-receiver-0.0.1-SNAPSHOT-jar-with-dependencies.jar

  async-sender-pull:
    build: async-sender-pull/
    image: async-sender-pull
    depends_on:
      - async-receiver-pull
    ports:
      - "10990"
      - "8084"
    links:
      - async-receiver-pull
    command: ./wait-for-it.sh async-receiver-pull:10991 --timeout=2 --strict -- java -jar async-sender-0.0.1-SNAPSHOT-jar-with-dependencies.jar

  async-clientapp:
    build: async-clientapp/
    image: async-clientapp
    depends_on:
      - async-sender-pull
    ports:
      - "8081"
    links:
      - async-sender-pull
    command: ./wait-for-it.sh async-sender-pull:10990 --timeout=2 --strict -- java -jar async-clientapp-0.0.1-SNAPSHOT-jar-with-dependencies.jar
