version: '3'

services:
  async-serverapp:
    build: async-serverapp/
    image: async-serverapp
    ports:
      - "8083"
      - "10992"

  async-receiver-pull:
    build: async-receiver-pull/
    image: async-receiver-pull
    depends_on:
      -  async-serverapp
    ports:
      - "10991"
      - "8082"
    links:
      - async-serverapp

  async-sender-pull:
    build: async-sender-pull/
    image: async-sender-pull
    depends_on:
      - async-receiver-pull
    ports:
      - "10990"
      - "8084"
    links:
      - async-receiver-pull

  async-clientapp:
    build: async-clientapp/
    image: async-clientapp
    depends_on:
      - async-sender-pull
    ports:
      - "8081"
    links:
      - async-sender-pull

  async-clientapp1:
    build: async-clientapp/
    image: async-clientapp
    depends_on:
      - async-sender-pull
    ports:
      - "8081"
    links:
      - async-sender-pull