// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package ifpb.grpc;

public interface MessageResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ifpb.grpc.MessageResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string hash = 2;</code>
   */
  java.lang.String getHash();
  /**
   * <code>string hash = 2;</code>
   */
  com.google.protobuf.ByteString
      getHashBytes();
}
