// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package ifpb.grpc;

public final class MessageOuterClass {
  private MessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ifpb_grpc_Id_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ifpb_grpc_Id_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ifpb_grpc_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ifpb_grpc_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ifpb_grpc_MessageResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ifpb_grpc_MessageResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMessage.proto\022\tifpb.grpc\"\020\n\002Id\022\n\n\002id\030\001" +
      " \001(\t\"#\n\007Message\022\n\n\002id\030\001 \001(\t\022\014\n\004text\030\002 \001(" +
      "\t\")\n\rMessageResult\022\n\n\002id\030\001 \001(\t\022\014\n\004hash\030\002" +
      " \001(\t2P\n\021SenderPullService\022;\n\013sendMessage" +
      "\022\022.ifpb.grpc.Message\032\030.ifpb.grpc.Message" +
      "Result2O\n\023ReceiverPullService\0228\n\010deliver" +
      "y\022\022.ifpb.grpc.Message\032\030.ifpb.grpc.Messag" +
      "eResult2I\n\020ServerAppService\0225\n\005print\022\022.i" +
      "fpb.grpc.Message\032\030.ifpb.grpc.MessageResu" +
      "ltB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ifpb_grpc_Id_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ifpb_grpc_Id_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ifpb_grpc_Id_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_ifpb_grpc_Message_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ifpb_grpc_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ifpb_grpc_Message_descriptor,
        new java.lang.String[] { "Id", "Text", });
    internal_static_ifpb_grpc_MessageResult_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ifpb_grpc_MessageResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ifpb_grpc_MessageResult_descriptor,
        new java.lang.String[] { "Id", "Hash", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
